DROP TABLE IF EXISTS NQUEUE;

CREATE TABLE NQUEUE (
NQ_ID INT NOT NULL AUTO_INCREMENT ,
NQ_DTR DATETIME NOT NULL ,
NQ_DAY INT DEFAULT '0' NOT NULL ,
NQ_MONTH INT DEFAULT '0' NOT NULL ,
NQ_YEAR INT DEFAULT '0' NOT NULL ,
NQ_HOUR INT DEFAULT '0' NOT NULL ,
NQ_MIN INT DEFAULT '0' NOT NULL ,
NQ_PRIORTIME VARCHAR( 50 ) NOT NULL ,
NQ_RULES VARCHAR( 255 ) NOT NULL ,
NQ_USERDB VARCHAR( 20 ) NOT NULL ,
U_ID VARCHAR( 20 ) NOT NULL ,
NT_ID CHAR( 10 ) NOT NULL ,
NQ_TYPE INT NOT NULL ,
NQ_TO VARCHAR( 255 ) NOT NULL ,
PRIMARY KEY ( NQ_ID ) ,
INDEX ( NQ_DTR ) 
) TYPE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS NQUPDATE;

CREATE TABLE NQUPDATE (
QU_ID INT NOT NULL AUTO_INCREMENT ,
QU_DTR DATETIME NOT NULL ,
QU_DAY INT DEFAULT '0' NOT NULL ,
QU_MONTH INT DEFAULT '0' NOT NULL ,
QU_YEAR INT DEFAULT '0' NOT NULL ,
QU_HOUR INT DEFAULT '0' NOT NULL ,
QU_MIN INT DEFAULT '0' NOT NULL ,
QU_PRIORTIME VARCHAR( 50 ) NOT NULL ,
QU_RULES VARCHAR( 255 ) NOT NULL ,
QU_USERDB VARCHAR( 20 ) NOT NULL ,
QU_U_ID VARCHAR( 20 ) NOT NULL ,
QU_NT_ID CHAR( 10 ) NOT NULL ,
QU_TYPE INT NOT NULL ,
QU_TO VARCHAR( 255 ) NOT NULL ,
QU_DELETE INT DEFAULT '0' NOT NULL ,
PRIMARY KEY ( QU_ID ) ,
INDEX ( QU_DTR ) 
) TYPE=MyISAM DEFAULT CHARSET=utf8;

