<?php
	define( "CONTACT_BASIC_TYPE", "CON" );
	define( "CONTACT_CONTACTGROUP_ID", "CONTACT" );
	define( "CONTACT_PHOTOGROUP_ID", "PHOTO" );
	define( "DEF_CONTACT_FOLDER", "1." );

	define( "CONTACT_FIELD", "FIELD" );
	define( "CONTACT_GROUP", "FIELDGROUP" );
	define( "CONTACT_FIELDS", "FIELDS" );
	define( "CONTACT_ALIGN", "ALIGN" );
	define( "CONTACT_DBFIELD", "DBFIELD" );
	define( "CONTACT_FIELDID", "ID" );
	define( "CONTACT_GROUPID", "ID" );
	define( "CONTACT_REQUIRED", "REQUIRED" );
	define( "CONTACT_MAXLEN", "MAXLEN" );
	define( "CONTACT_DECPLACES", "DECPLACES" );
	define( "CONTACT_REQUIRED_GROUP", "REQUIRED_GROUP" );
	define( "CONTACT_FIELDGROUPID", "GROUPID" );
	define( "CONTACT_FIELDGROUPNAME", "GROUPNAME" );
	define( "CONTACT_MENU", "MENU" );
	define( "CONTACT_MENU_SEPARATOR", "^&^" );

	define( "CONTACT_FIELDUNIQUE", "UNIQUE" );
	define( "CONTACT_FIELDMANDATORY", "MANDATORY" );

	define( "CONTACT_FIELDGROUP_LONGNAME", "LONG_NAME" );
	define( "CONTACT_FIELDGROUP_SHORTNAME", "SHORT_NAME" );

	define( "CONTACT_NAMEFIELD", "NAME" );
	define( "CONTACT_NAMEVALUE", "VALUE" );
	define( "CONTACT_IDFIELD", "ID" );
	define( "CONTACT_FIRSTNAMEFIELD", "C_FIRSTNAME" );
	define( "CONTACT_LASTNAMEFIELD", "C_LASTNAME" );
	define( "CONTACT_NICKNAMEFIELD", "C_NICKNAME" );
	define( "CONTACT_EMAILFIELD", "C_EMAILADDRESS" );
	define( "CONTACT_MIDNAMEFIELD", "C_MIDDLENAME" );

	//
	// Concact field types
	//

	define( "CONTACT_FIELD_TYPE", "TYPE" );
	define( "CONTACT_FT_TEXT", "TEXT" );
	define( "CONTACT_FT_URL", "URL" );
	define( "CONTACT_FT_EMAIL", "EMAIL" );
	define( "CONTACT_FT_MEMO", "MEMO" );
	define( "CONTACT_FT_NUMERIC", "NUMERIC" );
	define( "CONTACT_FT_MENU", "MENU" );
	define( "CONTACT_FT_DATE", "DATE" );
	define( "CONTACT_FT_IMAGE", "IMAGE" );

	define( "CONTACT_IMGF_FILENAME", "FILENAME" );
	define( "CONTACT_IMGF_SIZE", "SIZE" );
	define( "CONTACT_IMGF_DISKFILENAME", "DISKFILENAME" );
	define( "CONTACT_IMGF_TYPE", "TYPE" );
	define( "CONTACT_IMGF_MIMETYPE", "MIMETYPE" );
	define( "CONTACT_IMGF_DATETIME", "DATETIME" );
	define( "CONTACT_IMGF_MODIFIED", "MODIFIED" );
	define( "CONTACT_IMGF_PREVFILENAME", "PREVFILENAME" );

	define( "CONTACT_IMGF_IMAGE", "IMAGE" );
	define( "CONTACT_IMG_FILEPREFIX", "IMG" );	

?>