<?php
$descriptions = array(
	'rus'=>array(
		'includes'=>'файлы для первоначальной установки',
		'system'=>'новое ядро',
		'dblist'=>'настройки баз данных',		
		'kernel'=>'ядро',
		'temp'=>'временные файлы, логи',
		'data'=>'<strong>&larr; ваши файлы, защищенные сервером</strong>',
		'wbs.tgz'=>'архив со скриптами &larr; <strong>удалите после успешной установки</strong>',
		'shop/index.php'=>'подключение published/SC/html/scripts/index.php в случае, если не поддерживается mod_rewrite',
		'index.php'=>'работает только в случае выключенного mod_rewrite',
		'.htaccess'=>'основной .htaccess для скриптов WebAsyst',
		'published'=>'<strong>&larr; скрипты приложений и данные</strong>',
		'published/publicdata'=>'<strong>&larr; ваши файлы, доступные по www</strong>',
		'published/SC'=>'Shop-Script',
		'published/DD'=>'Файлы',
		'published/PD'=>'Фото',
		'published/QN'=>'Блокнот',
		'published/QP'=>'Страницы',
		'published/CM'=>'Контакты',
		'published/MM'=>'Почта',
		'published/MW'=>'Мой профиль',
		'published/AA'=>'Account administrator',
		'published/IT'=>'Задания',
		'published/PM'=>'Проекты',
		'published/WG'=>'Виджеты (кроме виджетов SC)',
		'published/UG'=>'Пользователи',
		'published/wbsadmin'=>'Инсталлер',
		'published/SC/html'=>'&larr; Shop-Script',
		'published/SC/html/scripts'=>'&larr; Shop-Script',
		'published/SC/html/scripts/modules'=>'различные модули',
		'published/SC/html/scripts/modules/auxpages'=>'информационные страницы',
		'published/SC/html/scripts/modules/news'=>'новости',
		'published/SC/html/scripts/modules/localization'=>'управление локализацией и языками',
		'published/SC/html/scripts/modules/discount_coupons'=>'дисконт-купоны',
		'published/SC/html/scripts/modules/feedback'=>'обратная связь',
		'published/SC/html/scripts/modules/linkexchange'=>'обмен ссылками',
		'published/SC/html/scripts/modules/payment'=>'модули оплаты',
		'published/SC/html/scripts/modules/shipping'=>'модули доставки',
		'published/SC/html/scripts/js'=>'JavaScript-библиотеки',
		'published/SC/html/scripts/smarty'=>'Smarty перенесен в ядро kernel/includes/smarty',
		'published/SC/html/scripts/repo_themes'=>'оригинальный файлы шаблонов дизайна (без изменений дизайн-редактора)',
		'published/SC/html/scripts/templates'=>'шаблоны отдельных компонентов магазина',
		'published/SC/html/scripts/templates/email'=>'email-уведомления',
		'published/SC/html/scripts/templates/backend'=>'администрирование',
		'published/SC/html/scripts/templates/frontend'=>'пользовательская часть',
		'published/SC/html/scripts/templates/sms'=>'SMS-уведомления',
		'published/SC/html/scripts/products_files'=>'файлы перенесены — смотрите data/%DB_KEY%/attachments/SC/products_files',
		'published/SC/html/scripts/products_pictures'=>'файлы перенесены — смотрите data/%DB_KEY%/attachments/SC/products_pictures',
		'published/common'=>'используется всеми приложениями',
		
		'kernel/errors.log'=>'общий лог ошибок',
		'dblist/wbs.log'=>'лог авторизаций в системе',
		'dblist/account.log'=>'лог изменений аккаунта',
		
	),
	'eng'=>array(
		'includes'=>'initial installation routine',
		'system'=>'new kernel',
		'dblist'=>'database settings',		
		'kernel'=>'kernel',
		'temp'=>'temp files and logs',
		'data'=>'<strong>&larr; data protected by server from public access</strong>',
		'wbs.tgz'=>'archive with applications source code &larr; <strong>delete after successful installation</strong>',
		'shop/index.php'=>'executes published/SC/html/scripts/index.php is case mod_rewrite feature is disabled',
		'index.php'=>'executed only is mod_rewrite is disabled',
		'.htaccess'=>'core .htaccess file for WebAsyst installation folder',
		'published'=>'<strong>&larr; applications sources and data</strong>',
		'published/publicdata'=>'<strong>&larr; data available for public http access</strong>',
		'published/SC'=>'Shop-Script',
		'published/DD'=>'Files',
		'published/PD'=>'Photos',
		'published/QN'=>'Notes',
		'published/QP'=>'Pages',
		'published/CM'=>'Contacts',
		'published/MM'=>'Mail',
		'published/MW'=>'My profile',
		'published/AA'=>'Account Administrator',
		'published/IT'=>'Issues',
		'published/PM'=>'Projects',
		'published/WG'=>'Widgets (except for SC)',
		'published/UG'=>'Users',
		'published/wbsadmin'=>'Installer',
		'published/SC/html'=>'&larr; Shop-Script',
		'published/SC/html/scripts'=>'&larr; Shop-Script',
		'published/SC/html/scripts/modules'=>'various modules',
		'published/SC/html/scripts/modules/auxpages'=>'info pages',
		'published/SC/html/scripts/modules/news'=>'news',
		'published/SC/html/scripts/modules/localization'=>'languages',
		'published/SC/html/scripts/modules/discount_coupons'=>'discount coupons',
		'published/SC/html/scripts/modules/feedback'=>'feedback form',
		'published/SC/html/scripts/modules/linkexchange'=>'link exchange',
		'published/SC/html/scripts/modules/payment'=>'payment modules',
		'published/SC/html/scripts/modules/shipping'=>'shipping modules',
		'published/SC/html/scripts/js'=>'JavaScript libraries',
		'published/SC/html/scripts/smarty'=>'Smarty — moved to kernel/includes/smarty',
		'published/SC/html/scripts/repo_themes'=>'original design theme files',
		'published/SC/html/scripts/templates'=>'templates of various storefront features',
		'published/SC/html/scripts/templates/email'=>'email notifications',
		'published/SC/html/scripts/templates/backend'=>'store admin mode',
		'published/SC/html/scripts/templates/frontend'=>'storefront',
		'published/SC/html/scripts/templates/sms'=>'SMS text message alerts',
		'published/SC/html/scripts/products_files'=>'moved to data/%DB_KEY%/attachments/SC/products_files',
		'published/SC/html/scripts/products_pictures'=>'moved to data/%DB_KEY%/attachments/SC/products_pictures',
		'published/common'=>'used by all applications',
		
		'kernel/errors.log'=>'common error log',
		'dblist/wbs.log'=>'user authorization log',
		'dblist/account.log'=>'account update log',
		
	),

);

$PatternDescriptions = array(
	'rus'=>array(
		'[(^|/)\.htaccess$]i'=>'настройки сервера Apache для этой папки',
		'[(^|/)\.svn($|/)]i'=>'файлы SVN',
		'(^data/[^/]+/attachments/SC/temp/usps_errors\.log$)i'=>'ошибки модуля USPS',
		'(^data/[^/]+/attachments/SC/temp/ss\.[\d]{4}\.[\d]{2}\.[\d]{2}\.log$)i'=>'журнал ошибок Shop-Script',
		'(^data/[^/]+/attachments/SC/temp/loc_cache/serlang[\d]+_[\w]{32}\.cch)i'=>'кеш локализации Shop-Script',
		'(^published/([\w]{2}|wbsadmin)/html$)i'=>'основные скрипты',
		'(^published/([\w]{2}|wbsadmin)/html/scripts$)i'=>'основные скрипты',
		'(^data/[^/]+/attachments/SC$)i'=>'файлы продуктов в Shop-Script',
		'(^data/[^/]+/attachments/SC/products_files$)i'=>'электронные продукты',
		'(^published/publicdata/[^/]+$)i'=>'общедоступные файлы приложений',
	),
	'eng'=>array(
		'[(^|/)\.htaccess$]i'=>'Apache settings for this folder',
		'[(^|/)\.svn($|/)]i'=>'SVN files',
		'(^data/[^/]+/attachments/SC/temp/usps_errors\.log$)i'=>'USPS module errors',
		'(^data/[^/]+/attachments/SC/temp/ss\.[\d]{4}\.[\d]{2}\.[\d]{2}\.log$)i'=>'Shop-Script error log',
		'(^data/[^/]+/attachments/SC/temp/loc_cache/serlang[\d]+_[\w]{32}\.cch)i'=>'Shop-Script localization cache',
		'(^published/([\w]{2}|wbsadmin)/html$)i'=>'source code files',
		'(^published/([\w]{2}|wbsadmin)/html/scripts$)i'=>'source code files',
		'(^data/[^/]+/attachments/SC$)i'=>'Shop-Script secure files',
		'(^data/[^/]+/attachments/SC/products_files$)i'=>'downloadable product files',
		'(^published/publicdata/[^/]+$)i'=>'data files available for public access',
	),
)
?>