<?php
	define('USAEPAY_TTL', 'USA ePay');
	define('USAEPAY_DSCR', 'Credit card processing through USA ePay payment gateway (www.usaepay.com)');
	
	define('USAEPAY_CFG_ORDERSTATUS_TTL', 'Order status after successful transaction');
	define('USAEPAY_CFG_ORDERSTATUS_DSCR', 'If you would like successfully processed orders to be automatically assigned a particular order status please select the status. Select "Default" to assign successful orders default new orders status (which is configured in "Configuration" screen of back end)');
	
	define('USAEPAY_CFG_SOURCEKEY_TTL', 'Source key');
	define('USAEPAY_CFG_SOURCEKEY_DSCR', 'Generated by the Merchant Console at www.usaepay.com.');
	
	define('USAEPAY_CFG_USD_TTL', 'USD currency type');
	define('USAEPAY_CFG_USD_DSCR', 'Order amount transferred to USA ePay web site is denominated in USD. Specify currency type in your shopping cart which is assumed as USD (order amount will be calculated according to USD exchange rate; if not specified exchange rate will be assumed as 1)');
	
	define('USAEPAY_CFG_TRANSMODE_TTL', 'Transaction type');
	define('USAEPAY_CFG_TRANSMODE_DSCR', 'Auth only - funds are authorized during purchase but not settled to your account automatically; Sale - funds are automatically cleared to your account. Contact USA ePay for details.');
	
	define('USAEPAY_TXT_AUTH', 'Auth only');
	define('USAEPAY_TXT_SALE', 'Sale');
	
	define('USAEPAY_TXT_DEFAULT', 'Default');
	
	define('USAEPAY_CFG_TESTMODE_TTL', 'Test mode');
	define('USAEPAY_CFG_TESTMODE_DSCR', '');
	
	define('USAEPAY_TXT_CCNUMBER', 'Credit card number');
	define('USAEPAY_TXT_CVV', 'CVV (3-digit number on the back of your card)');
	define('USAEPAY_TXT_EXPDATE', 'Expires');
	define('USAEPAY_TXT_ONLINEOREDER', 'Online order');
?>