<?php
	define('USAEPAY_TTL', 'USA ePay');
	define('USAEPAY_DSCR', '');
	
	define('USAEPAY_CFG_ORDERSTATUS_TTL', 'Order status after successful transaction');
	define('USAEPAY_CFG_ORDERSTATUS_DSCR', '');
	
	define('USAEPAY_CFG_SOURCEKEY_TTL', 'Source key');
	define('USAEPAY_CFG_SOURCEKEY_DSCR', 'Generated by the Merchant Console at www.usaepay.com.');
	
	define('USAEPAY_CFG_USD_TTL', 'USD currency type');
	define('USAEPAY_CFG_USD_DSCR', 'Order amount transferred to www.usaepay.com web site is denominated in USD. Specify currency type in your shopping cart which is assumed as USD (order amount will be calculated according to USD exchange rate; if not specified exchange rate will be assumed as 1)');
	
	define('USAEPAY_CFG_TRANSMODE_TTL', 'Transaction type');
	define('USAEPAY_CFG_TRANSMODE_DSCR', '');
	
	define('USAEPAY_TXT_AUTH', 'Auth only');
	define('USAEPAY_TXT_SALE', 'Sale');
	
	define('USAEPAY_TXT_DEFAULT', 'Default');
	
	define('USAEPAY_CFG_TESTMODE_TTL', 'Test mode');
	define('USAEPAY_CFG_TESTMODE_DSCR', '');
	
	define('USAEPAY_TXT_CCNUMBER', 'Credit card number');
	define('USAEPAY_TXT_CVV', 'CVV2');
	define('USAEPAY_TXT_EXPDATE', 'Expiration date');
	define('USAEPAY_TXT_ONLINEOREDER', 'Online order');
?>