<?php
	define( "HOST_DATABASE", "DATABASE" );
	define( "HOST_DBSETTINGS", "DBSETTINGS" );
	define( "HOST_PASSWORD", "PASSWORD" );
	define( "HOST_CREATEDATE", "CREATE_DATE" );
	define( "HOST_SIGNUP_DATETIME", "SIGNUP_DATETIME" );
	define( "HOST_EXPIRE_DATE", "EXPIRE_DATE" );
	define( "HOST_DATE_FORMAT", "DATE_FORMAT" );
	define( "HOST_DBSIZE_LIMIT", "DBSIZE_LIMIT" );
	define( "HOST_APPLICATIONS", "APPLICATIONS" );
	define( "HOST_LOGINHASHES", "LOGINHASHES" );
	define( "HOST_LOGINHASH", "LOGINHASH" );
	define( "HOST_ADVSETTINGS", "ADVSETTINGS" );
	define( "HOST_ADVPARAM", "PARAM" );
	define( "HOST_UNCONFIRMED", "UNCONFIRMED");
	define( "HOST_APPLICATION", "APPLICATION" );
	define( "HOST_APP_ID", "APP_ID" );
	define( "HOST_ADMINISTRATOR", "ADMINISTRATOR" );
	define( "HOST_TEMPLATE", "TEMPLATE" );
	define( "HOST_LANGUAGE", "LANGUAGE" );
	define( "HOST_READONLY", "READONLY" );
	define( "HOST_FIRSTLOGIN", "FIRSTLOGIN" );
	define( "HOST_LOGINNAME", "LOGINNAME" );
	define( "HOST_FIRSTNAME", "FIRSTNAME" );
	define( "HOST_LASTNAME", "LASTNAME" );
	define( "HOST_EMAIL", "EMAIL" );
	define( "HOST_COMPANYNAME", "COMPANYNAME" );
	define( "HOST_STATUS", "STATUS" );
	define( "HOST_STATUS_DELETED", "DELETED" );
	define( "HOST_DB_KEY", "DB_KEY" );
	define( "HOST_MAXUSERCOUNT", "MAX_USER_COUNT" );
	define( "HOST_RECIPIENTSLIMIT", "RECIPIENTS_LIMIT" );
	define( "HOST_SMS_RECIPIENTSLIMIT", "SMS_RECIPIENTS_LIMIT" );
	define( "HOST_DEFAULTENCODING", "DEFAULT_ENCODING" );
	define( "HOST_SQLSERVER", "SQLSERVER" );
	define( "HOST_DBNAME", "DB_NAME" );
	define( "HOST_DBPASSWORD", "DB_PASSWORD" );
	define( "HOST_TRIALDATASOURCE", "TRIAL_DATASOURCE" );
	define( "HOST_DBUSER", "DB_USER" );
	define( "HOST_DB_CREATE_OPTIONS", "DB_CREATE_OPTIONS" );
	define( "HOST_CREATE_OPTION", "CREATE_OPTION" );
	define( "HOST_DATABASE_USER", "DATABASE_USER" );
	define( "HOST_SOURCE", "SOURCE" );
	define( "HOST_DB_CREATE_OPTION", "DB_CREATE_OPTION" );
	define( "HOST_TEMPORARY", "TEMPORARY" );
	define( "HOST_BILLINGDATE", "BILLING_DATE" );
	define( "HOST_AUTORENEW", "AUTORENEW_MTO_ID" );

	define( "HOST_MODULES", "MODULES" );
	define( "HOST_ASSIGN", "ASSIGN" );
	define( "HOST_BALANCE", "BALANCE" );

	define( "HOST_ID", "ID" );
	define( "HOST_VALUE", "VALUE" );
	define( "HOST_CLASS", "CLASS" );
	define( "HOST_DISABLED", "DISABLED" );

	define( "HOST_DATABASE_USER_NEW", "DATABASE_USER_NEW" );
	define( "HOST_PASSWORD_NEW", "PASSWORD_NEW" );
	define( "HOST_DATABASE_USER_EXISTING", "DATABASE_USER_EXISTING" );
	define( "HOST_PASSWORD_EXISTING", "PASSWORD_EXISTING" );
	define( "HOST_DATABASE_NEW", "DATABASE_NEW" );
	define( "HOST_DATABASE_EXISTING", "DATABASE_EXISTING" );

	define( "HOST_SETTINGS", "SETTINGS" );
	define( "HOST_OPTION", "OPTION" );
	define( "HOST_OPTION_NAME", "NAME" );

	
	// new billing 
	//  
	define( "HOST_INSTALLED_FREE", 'DD,PD,CM,MM,PM,IT,QN,QP,SC' );
	define( "HOST_PLAN_NAME", "SET_PLAN" );
	define( "HOST_INSTALL_APPS", "INSTALL_APPS" );
	define( "HOST_DEFAULT_PLAN", "FREE" );
	define( "HOST_PLAN_DB", "PLAN" );
	define( "HOST_FREE_APPS", "FREE_APPS" );
	define( "HOST_CUSTOM_APPS", "CUSTOM_APPS" );

	define( "HOST_CUSTOM_PLAN", "CUSTOM" );
	define( "HOST_OLD_CUSTOM_PLAN", "PAID" );
	
	
	define( "HOST_RECIPIENTS_LIMIT", "-1" );
	define( "HOST_SMS_RECIPIENTS_LIMIT", "5" );
	
	define( "HOST_LOG_DEFINED_PLAN", 'PLAN:%s;PERIOD: %s;MAX_USER_COUNT:%s;USERS:%s'  );
	
	define( "HOST_SC_FIRST_REST", 'prod'  );
	define( "HOST_SC_SECOND_REST", 'mo'  );
?>